### ISSUE TITLE
Ship the Sarif formatter?

### ISSUE THREAD

**Issue by artivis** [alexmurray/bandit-snap#1]
Thanks for the snap :)

Would it be possible to ship the [`bandit-sarif-formatter`](https://github.com/microsoft/bandit-sarif-formatter) in this snap? 

Bandit does not natively support the sarif format and at the moment this formatter extension from microsoft is the way to go (see the [associated issue](https://github.com/PyCQA/bandit/issues/646)).

**Comment by alexmurray** [comment]
Hey @artivis, I'll see what I can do 😉

**Comment by artivis** [comment]
Thanks :)
